name: front-react-app-ci
on: 
  pull_request_review:
    types: ["submitted"]
  pull_request:
    types: ["opened"]
  push: 
    branches:
        - main
defaults:
  run:
    working-directory: codebase/rdicidr-0.1.0
jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '15'
      - name: install dependencies
        run: npm install
      - name: run linter
        run: npm run linter
      - name: install dependencies
        run: npm install
      - name: run linter
        run: npm run linter
      - name: Formatter (Prettier)
        run: npm run prettier --write
      - name: run tests (jest)
        run: CI=true npm run test
      - name: run bild
        run: npm run build